### ISSUE TITLE
throw warning for changing ConnectedFetch headers on the fly

### ISSUE THREAD

**Issue by goldylucks** [CharlesMangwa/react-data-fetching#15]
Wasted a good hour of my life on that now :)

I see a check for that [here](https://github.com/CharlesMangwa/react-data-fetching/blob/master/modules/ConnectedFetch.js#L85) but  that doesn't throw for me.

**Comment by CharlesMangwa** [comment]
Hey @goldylucks! I'm not sure I get your point here: do you mean that the check isn't working or am I wrong 😅?

**Comment by goldylucks** [comment]
yes, I tried changing headers on the fly and got no warning, just calls with the old headers

**Comment by CharlesMangwa** [comment]
Fixed (thanks to b5b3a591c13121930eae1cb4d4ac85cefc196755 =) )
