### ISSUE TITLE
Disable defaultHeaders

### ISSUE THREAD

**Issue by slavikdenis** [CharlesMangwa/react-data-fetching#17]
Is there a way, or can it be implemented to disable 'defaultHeaders' for the created requests?
I have tried to reset them by setting them to null / undefined but 'setRequestHeader' does not reset the header item.

**Comment by CharlesMangwa** [comment]
@slavikdenis Btw, can you tell me which headers precisely you want to remove, and why? Just out of curiosity :)

**Comment by slavikdenis** [comment]
At this time, I don't even remember :D But I think it had something to do with 'Content-Type' flag, but I guess I somehow manage to fix it on the back-end.

**Comment by CharlesMangwa** [comment]
OK got it! Hope the project went well 🙌
