### ISSUE TITLE
Error while fetching

### ISSUE THREAD

**Issue by Fausto95** [CharlesMangwa/react-data-fetching#2]
Hey there,
IDK why it gives me these errors

Running React & ReactDOM v16.2.0

<img width="678" alt="capture d ecran 2018-03-16 a 15 15 31" src="https://user-images.githubusercontent.com/23306911/37526102-d5fdab30-292e-11e8-95ee-1d6fe545848d.png">
<img width="996" alt="capture d ecran 2018-03-16 a 15 14 56" src="https://user-images.githubusercontent.com/23306911/37526103-d61cf6fc-292e-11e8-97c3-191f60c6263c.png">

**Comment by CharlesMangwa** [comment]
Hey @Fausto95! Just saw what could possibly be going wrong…but it's actually Friday afternoon here in Paris, so I'll fix this weekend! 😅 (just forgot to set up `babel-polyfill`, see [here](https://github.com/babel/babel/tree/master/packages/babel-preset-env#usebuiltins) and [here](https://stackoverflow.com/questions/33527653/babel-6-regeneratorruntime-is-not-defined))

**Comment by Fausto95** [comment]
Hey, solved this one with ``` import "regenerator-runtime/runtime";```
But there's another error !

**Comment by Fausto95** [comment]
Actually facing this one 
<img width="996" alt="capture d ecran 2018-03-16 a 16 19 04" src="https://user-images.githubusercontent.com/23306911/37528825-df58927e-2935-11e8-8970-1d60a4c3460b.png">

**Comment by CharlesMangwa** [comment]
Also see where this one is coming: fix coming this we!

**Comment by CharlesMangwa** [comment]
Thanks for letting me know about all this @Fausto95! Everything should be fine with the `v0.1.2` I just pushed. Ping me if any goes wrong again, otherwise: enjoy your we!
