### ISSUE TITLE
publish forked version of the repo

### ISSUE THREAD

**Issue by ad1992** [CharlesMangwa/react-data-fetching#32]
Since I am using this library and the version was not yet released with last bug fix so I changed the package name  to `react-fetching-data` and ran `yarn build`. After this `npm publish` worked successfully. I am able to install the package but when I try to require it it gives the below error
<img width="722" alt="screen shot 2018-09-19 at 9 49 35 pm" src="https://user-images.githubusercontent.com/11256141/45766737-f0068000-bc55-11e8-8bb4-b68d04ef6eff.png">

@CharlesMangwa can you tell me how can I publish the package ?

**Comment by newyork-anthonyng** [comment]
@ad1992 It looks like your `package.json` is referencing files like `cjs/react-data-fetching.js`, but your files are still named `react-fetching-data.js`.

**Comment by ad1992** [comment]
@newyork-anthonyng yes you are right the file name and entry in package.json was not matching. Thank you for pointing this out.
