### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by rafkhan** [CharlesMangwa/react-data-fetching#37]
I noticed that `requestToApi` uses XmlHttpRequest under the hood. Adding something to use plain `fetch` when on react-native would be a massive help.

I'd love to use this on my RN project and can definitely take a stab at making this contribution if there isn't enough bandwidth on your end 💯

**Comment by CharlesMangwa** [comment]
Hey @rafkhan! The main rationale behind the use of `XMLHttpRequest`over `Fetch` is because I wanted to have timeout and requests cancellation available on both React DOM & React Native, features which aren't supported yet by the `Fetch` API. That's basically it 😅

**Comment by rafkhan** [comment]
@CharlesMangwa ahhh, yeah, I've definitely run into that issue before. Good call lmao.

**Comment by rafkhan** [comment]
TIL XHRs are supported on react-native. whoops.
